Performing system checks...

System check identified no issues (0 silenced).
June 28, 2019 - 09:00:38
Django version 2.1.2, using settings 'WebBoard.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[28/Jun/2019 09:00:56] "GET / HTTP/1.1" 200 2688
[28/Jun/2019 09:00:56] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[28/Jun/2019 09:00:56] "GET /static/js/jquery-3.3.1.min.js HTTP/1.1" 304 0
[28/Jun/2019 09:00:56] "GET /static/css/app.css HTTP/1.1" 304 0
[28/Jun/2019 09:00:57] "GET /static/js/popper.min.js HTTP/1.1" 304 0
[28/Jun/2019 09:00:57] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[28/Jun/2019 09:21:56] "GET /login HTTP/1.1" 301 0
[28/Jun/2019 09:21:56] "GET /login/ HTTP/1.1" 200 1997
[28/Jun/2019 09:21:56] "GET /login/ HTTP/1.1" 200 1997
[28/Jun/2019 09:21:58] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[28/Jun/2019 09:21:58] "GET /static/js/popper.min.js HTTP/1.1" 304 0
[28/Jun/2019 09:21:58] "GET /static/js/jquery-3.3.1.min.js HTTP/1.1" 304 0
[28/Jun/2019 09:21:58] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[28/Jun/2019 09:21:58] "GET /static/css/app.css HTTP/1.1" 304 0
[28/Jun/2019 09:21:58] "GET /static/css/accounts.css HTTP/1.1" 200 201
[28/Jun/2019 09:21:58] "GET /static/css/accounts.css HTTP/1.1" 200 201
[28/Jun/2019 09:21:59] "GET / HTTP/1.1" 200 2688
[28/Jun/2019 09:21:59] "GET / HTTP/1.1" 200 2688
[28/Jun/2019 09:22:00] "GET /static/img/hip-square.png HTTP/1.1" 200 288573
[28/Jun/2019 09:22:21] "GET /boards/1 HTTP/1.1" 301 0
[28/Jun/2019 09:22:21] "GET /boards/1/ HTTP/1.1" 200 14309
[28/Jun/2019 09:22:22] "GET /boards/1/ HTTP/1.1" 200 14309
[28/Jun/2019 09:22:33] "GET /boards/1/topics/106 HTTP/1.1" 301 0
[28/Jun/2019 09:22:33] "GET /boards/1/topics/106/ HTTP/1.1" 200 4244
[28/Jun/2019 09:22:34] "GET /boards/1/topics/106/ HTTP/1.1" 200 4244
[28/Jun/2019 09:22:37] "GET /boards/1/topics/106/reply HTTP/1.1" 301 0
[28/Jun/2019 09:22:38] "GET /boards/1/topics/106/reply/ HTTP/1.1" 302 0
[28/Jun/2019 09:22:38] "GET /login/?next=/boards/1/topics/106/reply/ HTTP/1.1" 200 2024
[28/Jun/2019 09:22:38] "GET /boards/1/topics/106/reply/ HTTP/1.1" 302 0
[28/Jun/2019 09:22:39] "GET /login/?next=/boards/1/topics/106/reply/ HTTP/1.1" 200 2024
[28/Jun/2019 10:46:03] "GET /signup/ HTTP/1.1" 200 2819
[28/Jun/2019 10:46:04] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[28/Jun/2019 10:46:04] "GET /static/js/jquery-3.3.1.min.js HTTP/1.1" 304 0
[28/Jun/2019 10:46:04] "GET /static/js/popper.min.js HTTP/1.1" 304 0
[28/Jun/2019 10:46:04] "GET /static/css/accounts.css HTTP/1.1" 304 0
[28/Jun/2019 10:46:04] "GET /static/css/app.css HTTP/1.1" 304 0
[28/Jun/2019 10:46:04] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[28/Jun/2019 10:46:06] "GET /static/img/hip-square.png HTTP/1.1" 304 0
[28/Jun/2019 10:46:24] "POST /signup/ HTTP/1.1" 200 3124
[28/Jun/2019 10:46:44] "POST /signup/ HTTP/1.1" 200 3327
[28/Jun/2019 10:47:06] "POST /signup/ HTTP/1.1" 200 2982
[28/Jun/2019 10:52:38] "POST /signup/ HTTP/1.1" 302 0
[28/Jun/2019 10:52:38] "GET / HTTP/1.1" 200 3165
Performing system checks...

System check identified no issues (0 silenced).
June 28, 2019 - 10:44:03
Django version 2.1.2, using settings 'WebBoard.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f2541939ae8>
Traceback (most recent call last):
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django-nose'
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f46e448aae8>
Traceback (most recent call last):
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django-nose'
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fe1b70b2ae8>
Traceback (most recent call last):
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/home/admin/PracticePrograms/BoardProject/board/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django-nose'
Performing system checks...

System check identified no issues (0 silenced).
June 28, 2019 - 11:25:54
Django version 2.1.2, using settings 'WebBoard.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
June 28, 2019 - 11:28:36
Django version 2.1.2, using settings 'WebBoard.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
June 28, 2019 - 11:30:09
Django version 2.1.2, using settings 'WebBoard.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
